#!/bin/bash

if [[ -z "${MONITORING_TOOL__API_KEY}" ]] || [[ -z "${MONITORING_TOOL__BUILD_DIR}" ]] || [[ -z "${MONITORING_TOOL__SERVICE_NAME}" ]] || [[ -z "${MONITORING_TOOL__SERVICE_VERSION}" ]] || [[ -z "${MONITORING_TOOL__PUBLIC_PATH}" ]]; then
  echo "Some of required variables for sourcemaps upload are not set. Please check MONITORING_TOOL__API_KEY, MONITORING_TOOL__BUILD_DIR, MONITORING_TOOL__SERVICE_NAME, MONITORING_TOOL__SERVICE_VERSION, MONITORING_TOOL__PUBLIC_PATH"
  # TODO: show only absent variable
  echo "MONITORING_TOOL__API_KEY - $MONITORING_TOOL__API_KEY"
  echo "MONITORING_TOOL__SERVICE_NAME - $MONITORING_TOOL__SERVICE_NAME"
  echo "MONITORING_TOOL__SERVICE_VERSION - $MONITORING_TOOL__SERVICE_VERSION"
  echo "MONITORING_TOOL__BUILD_DIR - $MONITORING_TOOL__BUILD_DIR"
  echo "MONITORING_TOOL__PUBLIC_PATH - $MONITORING_TOOL__PUBLIC_PATH"
  exit 1
else
  DATADOG_API_KEY=$MONITORING_TOOL__API_KEY npx @datadog/datadog-ci sourcemaps upload "$MONITORING_TOOL__BUILD_DIR" \
            --service="$MONITORING_TOOL__SERVICE_NAME" \
            --release-version="$MONITORING_TOOL__SERVICE_VERSION" \
            --minified-path-prefix="$MONITORING_TOOL__PUBLIC_PATH"
fi
