name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: install package dependencies
        env:
          HUSKY: 0
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 2
          command: npm install --ci
      - name: Setup GitHub
        run: |
          git config user.name "kilo-github-ci"
          git config user.email "kilo-github-ci@users.noreply.github.com"
      - name: Run jest tests
        run: npm test
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
        run: |
          npm run build
          npm run semantic-release
